// SPDX-License-Identifier: GPL-2.0
//
// Author: Timon Stipkovits <timon2201@gmail.com>
//
// This software may be used and distributed according to the terms of the
// GNU General Public License version 2.

#ifndef DEFINES_H
#define DEFINES_H

#define SCHED_MODE_DSQ_PER_LLC 0
#define SCHED_MODE_DSQ_PER_CPU 1

#define NS_PER_US 1000ULL
#define NS_PER_MS 1000ULL * NS_PER_US

#define SLICE_SOFT (200 * NS_PER_US)
#define SLICE_LC (200 * NS_PER_US)
#define SLICE_INTERACTIVE (500 * NS_PER_US)
#define SLICE_NORMAL (500 * NS_PER_US)
#define SLICE_BATCH (500 * NS_PER_US)
#define SLICE_GREEDY (500 * NS_PER_US)

#define TASK_LAST_SPAWN_THRESH (160 * NS_PER_MS)
#define TASK_SPAWN_AVG_THRESH (140 * NS_PER_MS)

#define MAX_CONTINUOUS_SOFT_TIME (16 * NS_PER_MS)
#define MAX_CONTINUOUS_LC_TIME (32 * NS_PER_MS)
#define MAX_CONTINUOUS_INTERACTIVE_TIME (48 * NS_PER_MS)
#define MAX_CONTINUOUS_NORMAL_TIME (64 * NS_PER_MS)
#define MAX_CONTINUOUS_BATCH_TIME (80 * NS_PER_MS)

#define RUNTIME_PRIO_BOUNDARY_LC (200 * NS_PER_US)
#define RUNTIME_PRIO_BOUNDARY_INTERACTIVE (1000 * NS_PER_US)
#define RUNTIME_PRIO_BOUNDARY_NORMAL (2000 * NS_PER_US)
#define RUNTIME_PRIO_BOUNDARY_BATCH (8000 * NS_PER_US)

#define AVG_RUNTIME_PRIO_BOUNDARY_LC_DIVISOR 100LL
#define AVG_RUNTIME_PRIO_BOUNDARY_INTERACTIVE_DIVISOR 10LL
#define AVG_RUNTIME_PRIO_BOUNDARY_NORMAL_DIVISOR 2LL

#define RUNTIME_THRESH_PERCENT 5LL

#define MAX_RT_PRIO 100

#define MIN_AVG_RUNTIME 50ULL
#define MAX_RUNTIME_PER_TASK 4000000000ULL
#define MAX_AVG_RUNTIME_PER_CPU 8000000ULL
#define MIN_AVG_RUNTIME_PER_CPU 1000000ULL
#define GREEDY_MULTIPLICATOR 4ULL
#define ACCEPTABLE_MULTIPLICATOR 2ULL

#define HISTORIC_SPAWN_SAMPLES 5
#define HISTORIC_TASK_SAMPLES 4
#define HISTORIC_CPU_SAMPLES 100
#define AVG_RUNTIME_OVERRIDE_FACTOR 10

#define DSQ_TYPE_SOFT 1
#define DSQ_TYPE_LC 2
#define DSQ_TYPE_INTERACTIVE 3
#define DSQ_TYPE_NORMAL 4
#define DSQ_TYPE_BATCH 5
#define DSQ_TYPE_GREEDY 6
#define DSQ_TYPE_EMPTY 7
#define DSQ_PRIO_QUEUE_AMOUNT 6

#define SUBTREE_DECAY_HALFLIFE (8 * NS_PER_MS)                 /* cost halves every 8ms of wall time */
#define SUBTREE_DECAY_MAX_STEPS 16                             /* clamp: >16 halvings == effectively 0 */
#define SUBTREE_COST_GREEDY_THRESH (32 * NS_PER_MS)            /* demote spawner past this decayed cost */
#define SUBTREE_OVERRIDE_PROTECT_MAX_TIER DSQ_TYPE_SOFT        /* never subtree-demote <= this */

#define VLAG_PROMOTE_THRESH 4000000LL
#define VLAG_DEMOTE_THRESH -4000000LL

#define VLAG_MIN -6000000LL
#define VLAG_MAX 6000000LL
#define SLEEP_CREDIT_DIVISOR 1ULL
#define MAX_CREDITABLE_SLEEP 1000000LL

#define DEFAULT_DSQ_LOCAL_ON 0xC000000000000000ULL

#define DSQ_CPU_QUEUE_BASE_HARD 512
#define DSQ_CPU_QUEUE_BASE_SOFT 1024
#define DSQ_CPU_QUEUE_BASE_LC 1536
#define DSQ_CPU_QUEUE_BASE_INTERACTIVE 2048
#define DSQ_CPU_QUEUE_BASE_NORMAL 2560
#define DSQ_CPU_QUEUE_BASE_BATCH 3072
#define DSQ_CPU_QUEUE_BASE_GREEDY 3584

#define DSQ_LLC_QUEUE_BASE_SOFT 4160
#define DSQ_LLC_QUEUE_BASE_LC 4224
#define DSQ_LLC_QUEUE_BASE_INTERACTIVE 4288
#define DSQ_LLC_QUEUE_BASE_NORMAL 4352
#define DSQ_LLC_QUEUE_BASE_BATCH 4416
#define DSQ_LLC_QUEUE_BASE_GREEDY 4480

#define QUEUE_START DSQ_TYPE_BATCH

#define AVG_RUNTIME_START 5000000ULL

#define MAX_CPUS 512

#endif  // DEFINES_H
